# name: Autenticar Deploy em Produção consumindo API Key Segura do Cofre

# run-name: "Deploy via Cofre por: @${{ github.actor}}"

# on:
#   workflow_dispatch:

# jobs: 
#   Execucao_Segura:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Simular Autenticação
#         run: |
#           echo " Conectando ao servidor usando a chave: ${{ secrets.TOKEN_PRODUCAO}}"



name: Rollback de Emergencia

run-name: "🚨 ROLLBACK EMERGENCIAL da versao: ${{ inputs.versao_antiga }}" 

on:
  workflow_dispatch:
    inputs:
      token_seguranca: 
        description: Escreva o token de validaçao
        required: true
        type: string

      versao_antiga: 
        description: Selecione a versao para restauro 
        required: true
        type: choice
        options:
          - v1
          - v2
          - v3

jobs: 
  executar_rollback:
    runs-on: ubuntu-latest
    steps: 
      - name: Validar Token e Iniciar Rollback
        if: inputs.token_seguranca == secrets.TOKEN_PRODUCAO 
        run: echo "Senha correta Sucesso"

      - name: Token incorreto nao inicie o Rollback
        if: inputs.token_seguranca != secrets.TOKEN_PRODUCAO
        run: echo "Senha incorreta verifique e tente novamente"
