name: Autenticar Deploy em Produção consumindo API Key Segura do Cofre

run-name: "Deploy via Cofre por: @${{ github.actor}}"

on:
  workflow_dispatch:

jobs: 
  Execucao_Segura:
    runs-on: ubuntu-latest
    steps:
      - name: Simular Autenticação
        run: |
          echo " Conectando ao servidor usando a chave: ${{ secrets.TOKEN_PRODUCAO}}"