name: Pipeline Híbrido Global

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      ambiente_alvo:
        description: "Selecione o ambiente de execução"
        required: true
        type: choice
        options:
          - homologacao
          - producao
      token_seguranca:
        description: "Insira a chave token"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref}} 
  cancel-in-progress: true

run-name: "Pipeline acionada por @${{ github.actor}} via GATILHO ${{ github.event_name }} e a versao ${{github.run_number}}" 

jobs:
  test_matrix_job:
    outputs:  
      saida_1: ${{ steps.global.outputs.status_fase_1}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node_version: [18, 20]
    runs-on: ${{ matrix.os}}
    steps:
      - name: Criação de ficheiros
        run: |
          mkdir logs_teste
          echo "Matriz ok" > logs_teste/resultado.txt

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: teste-${{ matrix.os}}-${{ matrix.node_version}} # dinamico
          path: logs_teste

      - name: Output Global
        id: global
        run: |
          echo "status_fase_1=MATRIZ-CONCLUIDA" >> $GITHUB_OUTPUT             
    
  deploy_producao_job:
    needs: test_matrix_job
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'workflow_dispatch' && success()}}
    env:
      CHAVE_SISTEMA: ${{ secrets.TOKEN_PRODUCAO }} 
    environment: producao
    steps:
      - name: Download do Artefacto do Linux com Node-20
        if:  github.event.inputs.token_seguranca == env.CHAVE_SISTEMA 
        uses: actions/download-artifact@v8
        with:
          name: teste-ubuntu-latest-2
          path: ./pasta_deplo
      - name: 
        run: |
          cat ./pasta_deploy/resultado.txt

  notificar_falha_job:
    needs: [test_matrix_job, deploy_producao_job]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Alerta!!!!!!!!!!!!!!!!!!
        run: |
          echo "Alerta Máximo: A esteira falhou em algum ponto crítico."      

        