# name: Autenticar Deploy em Produção consumindo API Key Segura do Cofre

# run-name: "Deploy via Cofre por: @${{ github.actor}}"

# on:
#   workflow_dispatch:

# jobs: 
#   Execucao_Segura:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Simular Autenticação
#         run: |
#           echo " Conectando ao servidor usando a chave: ${{ secrets.TOKEN_PRODUCAO}}"



# name: Rollback de Emergencia 

# on:
#   workflow_dispatch:
#     inputs:
#       token_seguranca: 
#         description: Escreva o token de validaçao
#         required: true
#         type: string

#       versao_antiga: 
#         description: Selecione a versao para restauro 
#         required: true
#         type: choice
#         options:
#           - v1
#           - v2
#           - v3
# run-name: "🚨 ROLLBACK EMERGENCIAL da versao: ${{ inputs.versao_antiga }}"

# jobs: 
#   executar_rollback:
#     runs-on: ubuntu-latest
#     env:
#       TOKEN_PRODUCAO: ${{ secrets.TOKEN_PRODUCAO }}
#     steps: 
#       - name: Validar Token e Iniciar Rollback
    
#         if: github.event.inputs.token_seguranca == env.TOKEN_PRODUCAO
#         run: echo "Senha correta Sucesso"

#       - name: Token incorreto nao inicie o Rollback
#         if: github.event.inputs.token_seguranca != env.TOKEN_PRODUCAO
#         run: echo "Senha incorreta verifique e tente novamente"


name: Gerar ID de Build Dinamico e Compartilhar entre steps

run-name: "Execução do Build por @${{ github.actor}}"
on:
  workflow_dispatch:

jobs:
  Gerar_ID_Buid_Dinamico:
    runs-on: ubuntu-latest

    steps:
      - name: Criar o Dado
        id: gerador
        run: |
          echo "meu_id=BUILD-${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Exibir o ID Gerado
        run: |
          echo " O ID gerado foi: ${{ steps.gerador.outputs.meu_id}}"
